version: '3'
services: 
  front:
    build: react
    volumes:
      - ./react:/usr/src/app
    command: ["npm", "run", "dev"]
    ports: 
      - 8080:8080
  db:
    image: mysql:8.0.23
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ./mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: 
      - 3306:3306
  app:
    build: rails
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ./rails:/usr/src/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports: 
      - 3000:3000
    depends_on:
      - db